### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by ghost** [Cuevana/storm#128]

**Comment by Cuevana** [comment]
We launched a new version of the app, this issue should be fixed. Thank you.

**Comment by Draxler** [comment]
@Cuevana 
''.. issue should be fixed ..'' ? Is that mean we have to wait again for another Cuevana relese, to get English version of CuevanaStorm ?

**Update:**  i get explanation about Eng support. It seams we have to wait for a bug fix wich would happened ( i hope soon )..

**Comment by Cuevana** [comment]
English version is supported, but there is a bug in the latest version of node-webkit in Windows, that fails to detect OS language. We'll be updating as soon as a fix is available.

**Comment by Draxler** [comment]
Could this issue get reopened since issue is still present ?

**Comment by pepijn809** [comment]
Go here, mine is just new.
https://github.com/Cuevana/storm/issues/138

**Comment by Cuevana** [comment]
Fixed. See #138
